clear;
clc;
close all;

% Opening the files
Finger_Gen_File = 'finger_genuine.score';
Finger_Imp_File = 'finger_impostor.score';
Hand_Gen_File = 'hand_genuine.score';
Hand_Imp_File = 'hand_impostor.score';

formatSpec = '%f';

% Reading and extracting files
Gen_Finger_Array = fscanf(fopen(Finger_Gen_File,'r'),formatSpec);
Imp_Finger_Array = fscanf(fopen(Finger_Imp_File,'r'),formatSpec);
Gen_Hand_Array = fscanf(fopen(Hand_Gen_File,'r'),formatSpec);
Imp_Hand_Array = fscanf(fopen(Hand_Imp_File,'r'),formatSpec);
fclose('all');

Gen_Fing_Count = length(Gen_Finger_Array);
Imp_Fing_Count = length(Imp_Finger_Array);
Gen_Hand_Count = length(Gen_Hand_Array);
Imp_Hand_Count = length(Imp_Hand_Array);

fprintf('\tTotal number of Genuine and Imposter scores:\n')
disp(table({'Genuine';'Imposter'},[Gen_Fing_Count;Imp_Fing_Count],[Gen_Hand_Count;Imp_Hand_Count],'VariableNames',{'TotalCount' 'Finger' 'Hand'}))

%----------------------------------------------------------------------------------------------------------------------------------------------
% Min and Max
Fin_max = max(vertcat(Gen_Finger_Array,Imp_Finger_Array));
Fin_min = min(vertcat(Gen_Finger_Array,Imp_Finger_Array));
Han_max = max(vertcat(Gen_Hand_Array,Imp_Hand_Array));
Han_min = min(vertcat(Gen_Hand_Array,Imp_Hand_Array));

fprintf('\nMax and Min scores generated by each matcher:\n')
disp(table({'Maximum';'Minimum'},[Fin_max;Fin_min],[Han_max;Han_min],'VariableNames',{'Scores' 'Finger' 'Hand'}))

%-----------------------------------------------------------------------------------------------------------------------------------------------
% Finger Mean and Variance
Fin_Gen_mean = mean(Gen_Finger_Array);
Fin_Gen_vari = var(Gen_Finger_Array);
Fin_Imp_mean = mean(Imp_Finger_Array);
Fin_Imp_vari = var(Imp_Finger_Array);


fprintf('\nFinger Mean and Variance:\n')
disp(table({'Genuine';'Imposter'},[Fin_Gen_mean;Fin_Imp_mean],[Fin_Gen_vari;Fin_Imp_vari],'VariableNames',{'Finger' 'Mean' 'Variance'}))

%-----------------------------------------------------------------------------------------------------------------------------------------------
% Hand Mean and Variance
Han_Gen_mean = mean(Gen_Hand_Array);
Han_Gen_vari = var(Gen_Hand_Array);
Han_Imp_mean = mean(Imp_Hand_Array);
Han_Imp_vari = var(Imp_Hand_Array);

fprintf('\nHand Mean and Variance:\n')
disp(table({'Genuine';'Imposter'},[Han_Gen_mean;Han_Imp_mean],[Han_Gen_vari;Han_Imp_vari],'VariableNames',{'Hand' 'Mean' 'Variance'}))

%-----------------------------------------------------------------------------------------------------------------------------------------------
%D Prime Function

Finger_dprime = DPrime(Fin_Gen_mean,Fin_Imp_mean,Fin_Gen_vari,Fin_Imp_vari);
Hand_dprime = DPrime(Han_Gen_mean,Han_Imp_mean,Han_Gen_vari,Han_Imp_vari);

fprintf('\n D-prime Matcher scores for Hand and Finger:\n')
disp(table({'Finger';'Hand'},[Finger_dprime;Hand_dprime],'VariableNames',{'Scores' 'DPrime'}))
%-----------------------------------------------------------------------------------------------------------------------------------------------
% Histogram Finger
histogram(Gen_Finger_Array);
hold on 
histogram(Imp_Finger_Array);


legend('Genuine', 'Imposter')

title('Histogram of Fingers')
xlabel('Number of scores')
ylabel('Scores Distribution')

%Histogram Hand
figure;
histogram(Gen_Hand_Array);
hold on 
histogram(Imp_Hand_Array);

legend('Genuine', 'Imposter')

title('Histogram of Hand')
xlabel('Number of scores')
ylabel('Scores Distribution')
%-----------------------------------------------------------------------------------------------------------------------------------------------
% FNMR and FMR

Finger_FNMR = FNMR(Gen_Finger_Array,32);
Finger_FMR = FMR(Imp_Finger_Array,32);

Hand_FNMR = FNMRDIS(Gen_Hand_Array,45);
Hand_FMR = FMRDIS(Imp_Hand_Array,45);

fprintf('\nFinger and Hand FMR,FNMR Calculations:\n')
disp(table({'Finger';'Hand'},[Finger_FMR;Hand_FMR],[Finger_FNMR;Hand_FNMR],'VariableNames',{'Threshold' 'FMR' 'FNMR'}))

%-----------------------------------------------------------------------------------------------------------------------------------------------
%ROC Curves
fprintf('\nCalclating the ROC curve with the given genuine and impostor scores: \n')

in = input('Would you like to provide Genuine and Imposter scores set [Y/N]: ','s');

if(in == 'Y')
 
    gen = input('Genuine Scores file: ','s');
    imp = input('Imposter Scores file: ','s');
    
    option = input('What kind of scores are they: \n1)Distance\n2)Similarity\n Type 1 or 2: ','s')

    GEN = fscanf(fopen(gen,'r'),formatSpec);
    IMP = fscanf(fopen(imp,'r'),formatSpec);
    
    
    Start_Array = min([GEN;IMP]);
    End_Array = max([GEN;IMP]);
    
    if(Start_Array == 0)
    Start_Array = 1;
    end
    if(End_Array == 0)
        End_Arrya = 1;
    end
    
    Hand_Gen_ROC = 1:End_Array;
    Hand_Imp_ROC = 1:End_Array;
    
    if(option == '1')
    
        [Hand_Imp_ROC, Han_Gen_ROC] = ROCDIS(GEN,IMP,Start_Array,End_Array);
    elseif(option == '2')
        [Hand_Imp_ROC, Han_Gen_ROC] = ROC(GEN,IMP,Start_Array,End_Array); 
    end

    if(EER_Number ~= -1)
        fprintf('EER Number = %d\n',EER_Number);
    else
        fprintf('ERR Number does not exisit!\n');
    end


    plot(Hand_Imp_ROC,Hand_Gen_ROC)

    title('Input ROC Curve')
    xlabel('FMR(FAR)')
    ylabel('FNRM(FRR)')
end

in2 = input('Display the ROC Curves of Hand and Finger? [Y/N]: ','s');
if(in2 == 'Y')
    fprintf('\nHand and Fingers ROC Curves. \nHand:\n')
    Start_Array = min([Gen_Hand_Array;Imp_Hand_Array]);
    End_Array = max([Gen_Hand_Array;Imp_Hand_Array]);

    if(Start_Array == 0)
        Start_Array = 1;
    end
    if(End_Array == 0)
        End_Arrya = 1;
    end

    Hand_Gen_ROC = 1:End_Array;
    Hand_Imp_ROC = 1:End_Array;

    [Hand_Imp_ROC, Hand_Gen_ROC] = ROCDIS(Gen_Hand_Array,Imp_Hand_Array,Start_Array,End_Array);

    figure;
    plot(Hand_Imp_ROC,Hand_Gen_ROC)

    title('Hand ROC Curve')
    xlabel('FMR(FAR)')
    ylabel('FNRM(FRR)')
    
   
    fprintf('\nFinger:\n')
    Start_Array = min([Gen_Finger_Array;Imp_Finger_Array]);
    End_Array = max([Gen_Finger_Array;Imp_Finger_Array]);

    if(Start_Array == 0)
        Start_Array = 1;
    end
    if(End_Array == 0)
        End_Arrya = 1;
    end

    Fin_Gen_ROC = 1:End_Array;
    Fin_Imp_ROC = 1:End_Array;

    [Fin_Imp_ROC, Fin_Gen_ROC] = ROC(Gen_Finger_Array,Imp_Finger_Array,Start_Array,End_Array);
    
    figure;
    plot(Fin_Imp_ROC,Fin_Gen_ROC)

    title('Finger ROC Curve')
    xlabel('FMR(FAR)')
    ylabel('FNRM(FRR)')
    
    figure;
    x = 0:1;
    y = x;
    
    
    plot(Fin_Imp_ROC,Fin_Gen_ROC)
    hold on 
    plot(Hand_Imp_ROC,Hand_Gen_ROC)
    hold on 
    plot(x,y)
    grid on
    
    
    title('Both ROC Curve')
    legend('Finger', 'Hand')
    xlabel('FMR(FAR)')
    ylabel('FNRM(FRR)')
 
 end
%-----------------------------------------------------------------------------------------------------------------------------------------------
%-----------------------------------------------------------------------------------------------------------------------------------------------
%-----------------------------------------------------------------------------------------------------------------------------------------------
%-----------------------------------------------------------------------------------------------------------------------------------------------
%-----------------------------------------------------------------------------------------------------------------------------------------------

